version: "3.9"

services:
    nginx:
        build:
            context: docker/nginx
        volumes:
            - ./app:/var/www
        depends_on:
            - php
        ports:
            - "${NGINX_PORT}:80"
    php:
        build:
            context: docker/php-fpm
        volumes:
            - ./app:/var/www
        depends_on:
            - mysql
    mysql:
        image: mysql:${DATABASE_VERSION}
        ports:
            - "${DATABASE_PORT}:3306"
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        volumes:
            - ./docker/database/data:/var/lib/mysql
